import { useState } from "react";

export default function App() {
  const [showAnswer, setShowAnswer] = useState(false);
    const [fileName, setFileName] = useState("");

      const subjects = [
          "Anatomy",
              "Physiology",
                  "Biochemistry",
                      "Pathology",
                          "Pharmacology",
                              "Microbiology",
                                  "Forensic Medicine",
                                      "Community Medicine",

                                          "ENT",
                                              "Ophthalmology",
                                                  "Dermatology",
                                                      "Psychiatry",
                                                          "Radiology",
                                                              "Anesthesiology",

                                                                  "General Medicine",
                                                                      "General Surgery",
                                                                          "Orthopedics",
                                                                              "Pediatrics",
                                                                                  "Obstetrics & Gynecology",

                                                                                      "Toxicology",
                                                                                          "Emergency Medicine"
                                                                                            ];

                                                                                              return (
                                                                                                  <div style={{ padding: "20px", fontFamily: "Arial" }}>
                                                                                                        <h1>🧠 NEET PG Rapid Cards</h1>

                                                                                                              <div
                                                                                                                      style={{
                                                                                                                                border: "1px solid gray",
                                                                                                                                          padding: "20px",
                                                                                                                                                    borderRadius: "10px",
                                                                                                                                                              marginBottom: "20px"
                                                                                                                                                                      }}
                                                                                                                                                                            >
                                                                                                                                                                                    🔥 Streak: 7 days <br />
                                                                                                                                                                                            🎯 Due today: 20 cards <br />
                                                                                                                                                                                                    ⭐ Weak topics: 12
                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                <div
                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                  border: "1px solid gray",
                                                                                                                                                                                                                                            padding: "20px",
                                                                                                                                                                                                                                                      borderRadius: "10px",
                                                                                                                                                                                                                                                                marginBottom: "20px"
                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                      <h2>Today's Revision</h2>

                                                                                                                                                                                                                                                                                              <h3>Best antidote for lead poisoning?</h3>

                                                                                                                                                                                                                                                                                                      {!showAnswer ? (
                                                                                                                                                                                                                                                                                                                <button onClick={() => setShowAnswer(true)}>
                                                                                                                                                                                                                                                                                                                            Show Answer
                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                                                                    <h3>Calcium disodium EDTA</h3>

                                                                                                                                                                                                                                                                                                                                                                                <button>😄 Easy</button>

                                                                                                                                                                                                                                                                                                                                                                                            <button style={{ marginLeft: "10px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                          😐 Medium
                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                  <button style={{ marginLeft: "10px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                😵 Hard
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>📚 Subjects</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {subjects.map((subject) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={subject}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    margin: "10px 0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: "10px"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        📘 {subject}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <br />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>📄 Import Notes</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setFileName(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              e.target.files?.[0]?.name || ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {fileName && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Imported: {fileName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }